spring:
  application:
    name: url-shortner
  datasource:
    url: jdbc:mysql://localhost:3306/url-shortner?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

access:
  allow:
    origin: "*"

jwt:
  secret: ba383a49ae67b40a56c02aa52548721a7b040aa40ea49a6ffe1d09f828b4873b
  expiration: 172800000
